### PR TITLE
Docker 4.7

### PR DESCRIPTION
**Pull request by pooja-jain-17**
Updated Dockerfile to build HammerDB 4.7
Updated the Ubuntu image to be used to 22.04 from 20.04
Modified the Docker image entry point command to support Kubernetes. #495 
Updated MSSQL Client libraries #496 
Added GUI support to the Dockerfile #497 
Added Database specific Dockerfiles to maintain lightweight containers. #506 
Deleted explicit addition of example scripts, now that they are part of HammerDB 4.7 bundle #509 
Updated Readme to reflect the latest changes.

### CODE REVIEW

**Review by sm-shaw — CHANGES_REQUESTED** [review]
1. 

Default version of python has changed in Ubuntu but not in HammerDB built on 20.04. 

```
# ./hammerdbcli py
HammerDB CLI v4.7
Copyright (C) 2003-2023 Steve Shaw
Type "help()" for a list of commands
Error: Python version 3.8 required, version 3.10.6 is installed
```
This should be changed to install version 3.8 instead. 
```
#Install Python3.8
RUN apt install -y python3
```

2. 

Is it possible to distinguish the image name of database specific dockerfiles from the one that includes all databases? This way they could be installed side by side. 

3. 

Can we change the main readme file and database specific readmes in the directories to be named Readme.md and updated in markdown format. An example from the main HammerDB readme is shown below. This way it will be more readable when browsing the files from GitHub. 

--
# HammerDB

HammerDB is the leading benchmarking and load testing software for the worlds most popular databases supporting Oracle Database, Microsoft SQL Server, IBM Db2, PostgreSQL, MySQL and MariaDB.

## Credits

- Steve Shaw
- [All Contributors](https://github.com/TPC-Council/HammerDB/contributors)

## License

GNU General Public License v3.0. Please see [License File](LICENSE) for more information.

## Support

- [Contact information](http://www.hammerdb.com)
- [Documentation](https://www.hammerdb.com/docs)
--

**Comment by pooja-jain-17** [comment]
Thanks for the review. 
1. I will update the Python version. I did not realize the default python3 version is different on Ubuntu 22.04.
2. All the database specific docker images can be built side by side with different tags, just as we do with different hammerdb versions. The Readme file for each database outlines how an image for that database can be built with a tag. 
   Ex:  
To create an image: Go to the folder containing the Dockerfile
```
docker build -t hammerdb:mssqls .
docker run -it --name hammerdb-mssqls hammerdb:mssqls bash
```
I have all database specific images built this way:
```
docker images
REPOSITORY             TAG        IMAGE ID       CREATED        SIZE
hammer                 mssqls     2113ce413d42   45 hours ago   578MB
hammer                 oracle     0789217a574d   45 hours ago   760MB
hammer                 postgres   3609a867bdcd   45 hours ago   445MB
hammer                 mysql      168db390a6cd   46 hours ago   438MB
hammer                 maria      f7bc51430f51   46 hours ago   432MB
```

Alternatively, if you meant, if we could have database specific Dockerfile names as below so all are placed under one directory, that's doable too.
```
mysql.dockerfile
oracle.dockerfile
maria.dockerfile
```
3. Sure I can Update the Readme files. 

Thanks,
Pooja

**Comment by pooja-jain-17** [comment]
For the requested changes:
1. Reverted back to Ubuntu 20.04,  HammerDB 4.7 requires Python3.8.10, Whereas Ubuntu 22.04 supports Python3.8.16. We can upgrade to Ubuntu 22.04 in the next release when this dependency is cleared. 
2.  Leaving as is. If there is need to have all Dockerfiles in a single directory, please mention and this can be updated.
3. Updated Main Readme and all database specific Readme to Readme.md markdown format.

**Review by sm-shaw — APPROVED** [review]

**Comment by sm-shaw** [comment]
Thank-you for the changes and the explanation about building the different lightweight images. I have retested by doing a build, this all looks great, and I have approved.

**Review by abondvt89 — APPROVED** [review]

**Comment by abondvt89** [comment]
Approving with two reviews until Code Maintenance Team expands back to three members

**Pull request merged**
