### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by fluesvamp**
Build/Bawt-2.1.0/Bawt.tcl
ChangeLog
DocBook/docs.xml
agent/agent
images/icons.tcl
modules/comm-4.5.6.tm
modules/etprof-1.1.tm
modules/huddle-0.3.tm
modules/json-1.3.4.tm
modules/promise-1.1.0.tm
modules/reformat_tcl-1.0.tm
modules/rest-1.4.tm
modules/socktest-0.2.tm
modules/tablelist_tile-5.18.tm
modules/task-1.1.1.tm
modules/tkcon-2.4.tm
modules/tooltip-1.4.6.tm
modules/xtprof-1.0.tm
src/generic/gencnv.tcl
src/generic/gened.tcl
src/generic/gengen.tcl
src/generic/genhelp.tcl
src/generic/genstep.tcl
src/mariadb/mariaopt.tcl
src/mysql/mysqlopt.tcl
src/oracle/oramet.tcl
src/postgresql/pgmet.tcl
src/postgresql/pgoltp.tcl
src/trafodion/trafoltp.tcl

### CODE REVIEW

**Review by sm-shaw — APPROVED** [review]
Have reviewed all changes and confirm that all typos fixed are in comments or message output so fine to accept.

**Comment by fluesvamp** [comment]
this is ready to merge

the docs.xml file might be revisited at some point

for example, this appears in the online rendered commit

```diff
-       generated data is delimited by a pip character ie “|” and intended NULL
+       generated data is delimited by a pip character, i.e. “|” and intended NULL
```

should be pipe not pip

**Review by abondvt89 — APPROVED** [review]

**Review by memmertoIBM — APPROVED** [review]

**Comment by memmertoIBM** [comment]
In addition to further review on docs.xml, the changes in modules/* need to be propagated upstream at some point.

**Comment by abondvt89** [comment]
Merging as approved by all members of the code maintenance team

**Pull request merged**
