### PR TITLE
Docbook Documentation v4.0

### PR DESCRIPTION
**Pull request by sm-shaw**
Documentation updates for v4.0. All screenshots updated for nomenclature changes.

### CODE REVIEW

**Comment by elfordINTC** [comment]
is there a postprocessed version of this somewhere to look at?

**Comment by sm-shaw** [comment]
Link to postprocessed version sent to tpc-oss mailgroup or XML version can be viewed and updated with DocBook Editor such as XMLMind https://www.xmlmind.com/index.html

**Comment by elfordINTC** [comment]
thanks!  Still mining thru my mailbox from my vacation day.

**Comment by abondvt89** [comment]
Accepting pull request as voted on November 3, 2020 in the TPC-OSS subcommittee.

**Pull request merged**
