### PR TITLE
Add sslmode support for PostgreSQL database

### PR DESCRIPTION
**Pull request by christianricci**
Allow pg_sslmode argument to be passed into the postgres driver. Keep default argument value to prefer to make it compatible with default postgres value (refer to https://www.postgresql.org/docs/13/libpq-ssl.html)

pg_sslmode can be changed as follows:

    hammerdb>dbset db pg
    Database set to PostgreSQL

    hammerdb>print dict
    Dictionary Settings for PostgreSQL
    connection {
     pg_host    = localhost
     pg_port    = 5432
     pg_sslmode = prefer
    }
    ...

    hammerdb>diset connection pg_sslmode disable
    Changed connection:pg_sslmode from prefer to disable for PostgreSQL

    hammerdb>print dict
    Dictionary Settings for PostgreSQL
    connection {
     pg_host    = localhost
     pg_port    = 5432
     pg_sslmode = disable
    }
    ...

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

### CODE REVIEW

**Comment by sm-shaw** [comment]
I have run tests on the changes. Overall, most of the implementation is fine, although some options when selected give errors and need updates. So far the issues identified are: 
1. As noted initially the **GUI** needs updating to include an option to set the sslmode. This is need in both the **TPROC-C** and **TPROC-H** interfaces as well as the **Transaction Counter** interface. 
2. **Transaction Counter** doesn't work for either **TPROC-C** or **H** giving error invalid sslmode value: "user login" - looks like the arguments are being passed in the wrong order. 
3. **TPROC-C** 
a. When selecting asynchronus scaling it errors with can't read sslmode no such variable. 
b. Connect Pooling option  errors with can't read sslmode no such variable. Needs updating to include SSL option in the XML configuration in the connectpool directory.
4. **TPROC-H**
a. When Refresh option is selected, it errors with wrong # of args - looks like there is an extra sslmode parameter in the wrong order.
I will take a look at fixing these issues and submitting an update to the pull request.

**Comment by sm-shaw** [comment]
I have created a branch on my fork https://github.com/sm-shaw/HammerDB/tree/pg-sslmode with additional commits that address the issues.  More testing is needed to validate all the updates, but once this is done I will create a pull request back to christianricci:pg-sslmode and once accepted this should be good to accept into the main HammerDB repository.

An example of the GUI with the prefer SSL mode update is shown. On is enable, off is disable and the correct option appears in the build or driver script as required. 

pgopt

**Comment by christianricci** [comment]
Thanks for taking a look and fixing the bugs, also for adding the UI changes. It looks great !!!

**Comment by sm-shaw** [comment]
I have done some more tests and found and fixed one more issue when the asynchronous connections and connect pooling were selected at the same time. I have opened a pull request to your branch here https://github.com/christianricci/HammerDB/pull/1. Once accepted, this should update the pull request to the main HammerDB repository with the changes needed.

**Comment by christianricci** [comment]
Thanks Steve. I have squashed/merged your changes into my pull request.

**Comment by sm-shaw** [comment]
Great, this has now been reviewed and tested all the changes needed are now in the Pull Request.  All Pull Requests are discussed by the TPC-OSS subcommittee, so this will be discussed at the next meeting, and accepted subject to approval.

**Comment by sm-shaw** [comment]
For additional clarity the contribution says "BSD-new" license (rather than BSD-Free) which is the Modified BSD as described here by the FSF: https://www.gnu.org/licenses/license-list.html#ModifiedBSD

Modified BSD license (#ModifiedBSD)
This is the original BSD license, modified by removal of the advertising clause. It is a lax, permissive non-copyleft free software license, **compatible with the GNU GPL.**

Therefore, according to the FSF it is fine to take the contribution as "BSD-new" and include it in HammerDB which is GPLv3 without modifying the contribution to be GPL first, @christianricci is this your understanding as well?

**Comment by abondvt89** [comment]
Thanks Steve for correcting my error.  I think my brain was used to associating the word Free with the word BSD (FreeBSD) ;-). Yes, the license in question is BSD-new.  It sounds like it should be fine to accept.  @christianricci is that your interpretation as well?

**Comment by christianricci** [comment]
I believe this contribution is meant to be "Free of Use". I'll confirm with my colleagues and update you shortly.

**Comment by sm-shaw** [comment]
Accepting pull request as voted on September 14, 2021 in the TPC-OSS subcommittee.

**Comment by christianricci** [comment]
Thanks Steve, most appreciated your bug fixes and UI contribution.

**Pull request merged**
