### PR TITLE
Add Optional Invisible Primary Key to History for Replication in MySQL and MariaDB

### LINKED ISSUE #580: Add PK to be able to bench group replication in MySQL
https://github.com/TPC-Council/HammerDB/blob/8ad6b64472fa8ee8fc60b51267a50847876b296b/src/mysql/mysqloltp.tcl#L555

Hello,

Could you add these lines to add an invisible PK to the table history ?
  `id` INT NOT NULL AUTO_INCREMENT INVISIBLE,
PRIMARY KEY (`id`)

for the whole table:
```
    set sql(3) "CREATE TABLE `history` (
  `h_c_id` INT NULL,
  `h_c_d_id` INT NULL,
  `h_c_w_id` INT NULL,
  `h_d_id` INT NULL,
  `h_w_id` INT NULL,
  `h_date` DATETIME NULL,
  `h_amount` DECIMAL(6, 2) NULL,
  `h_data` VARCHAR(24) BINARY NULL,
  `id` INT NOT NULL AUTO_INCREMENT INVISIBLE,
PRIMARY KEY (`id`)
)
ENGINE = $mysql_storage_engine"
```

It works for me.

Sincerely,
Martin

### PR DESCRIPTION
**Pull request by sm-shaw**
Pull Request adds an optional primary key for the history table which is needed for replication. 

mysqlhistorypk

option mysql/maria_history_pk is added to the config/CLI. 
```
<schema>
            <mysql_count_ware>1</mysql_count_ware>
            <mysql_num_vu>1</mysql_num_vu>
            <mysql_user>root</mysql_user>
            <mysql_pass>mysql</mysql_pass>
            <mysql_dbase>tpcc</mysql_dbase>
<mysql_storage_engine>innodb</mysql_storage_engine>
            <mysql_partition>false</mysql_partition>
            <mysql_prepared>false</mysql_prepared>
            <mysql_history_pk>false</mysql_history_pk>
        </schema>
```
Change will check that the InnoDB storage engine is being used and that the MySQL/MariaDB version is at a level that supports inivisible primary keys before adding one. If not it falls back to the default option. 

Example change in table with and without. 
```
mysql> show create table history\G
*************************** 1. row ***************************
       Table: history
Create Table: CREATE TABLE `history` (
  `h_c_id` int DEFAULT NULL,
  `h_c_d_id` int DEFAULT NULL,
  `h_c_w_id` int DEFAULT NULL,
  `h_d_id` int DEFAULT NULL,
  `h_w_id` int DEFAULT NULL,
  `h_date` datetime DEFAULT NULL,
  `h_amount` decimal(6,2) DEFAULT NULL,
  `h_data` varchar(24) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `id` int NOT NULL AUTO_INCREMENT /*!80023 INVISIBLE */,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30001 DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
*************************** 1. row ***************************
       Table: history
Create Table: CREATE TABLE `history` (
  `h_c_id` int DEFAULT NULL,
  `h_c_d_id` int DEFAULT NULL,
  `h_c_w_id` int DEFAULT NULL,
  `h_d_id` int DEFAULT NULL,
  `h_w_id` int DEFAULT NULL,
  `h_date` datetime DEFAULT NULL,
  `h_amount` decimal(6,2) DEFAULT NULL,
  `h_data` varchar(24) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
```
When testing on an incompatible version

```
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.20    |
+-----------+
1 row in set (0.00 sec)
```
Message is reported the minimum supported version but continues anyway without the invisible PK.
```
Hammerdb Log @ Tue Aug 22 15:18:16 BST 2023
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
Vuser 1:Monitor Thread
Vuser 1:CREATING TPCC2 SCHEMA
Vuser 1:Ssl_cipher
Vuser 1:CREATING DATABASE tpcc2
Vuser 1:CREATING TPCC TABLES
Vuser 1:Minimum MySQL version for invisible PK is 8.0.30
Vuser 1:Loading Item
```
This way it should allow adding the primary key for replication where it is needed, but also provide minimal disruption where it is not. 

Same change in MySQL and MariaDB

### CODE REVIEW

**Review by jamiere-msft — APPROVED** [review]

**Review by abondvt89 — APPROVED** [review]

**Comment by abondvt89** [comment]
Merging after reviews and approval of the three members of the code maintenance team.

**Comment by shatshen** [comment]
Hi can you make this generated PK usable for 8.4.6 MySQL?

**Comment by sm-shaw** [comment]
Hi its an option you need to select in versions at or above 8.0.30 
In v6.0 there is also change to allow for MySQL forks that don't strictly comply to the standard version numbers:
https://github.com/TPC-Council/HammerDB/commit/73a4f713f27f167148dfedb220481f481823034f

**Comment by shatshen** [comment]
hammerdb>
Dictionary Settings for MySQL
connection {
 mysql_host               = 192.168.0.1
 mysql_port               = 3306
 mysql_socket             = /tmp/mysql.sock
 mysql_ssl                = false
 mysql_ssl_two_way        = false
 mysql_ssl_linux_capath   = /etc/mysql/certs
 mysql_ssl_windows_capath = C:\mysql\certs
 mysql_ssl_ca             = ca-cert.pem
 mysql_ssl_cert           = client-cert.pem
 mysql_ssl_key            = client-key.pem
 mysql_ssl_cipher         = server
 mysql_oceanbase_port     = 2881
}
tpcc       {
 mysql_count_ware       = 500
 mysql_num_vu           = 16
 mysql_user             = hammerdb
 mysql_pass             = P@ssw0rd
 mysql_dbase            = tpcc
 mysql_storage_engine   = innodb
 mysql_partition        = false
 mysql_prepared         = false
 mysql_history_pk       = true
 mysql_no_stored_procs  = false
 mysql_total_iterations = 10000000
 mysql_raiseerror       = false
 mysql_keyandthink      = false
 mysql_driver           = timed
 mysql_rampup           = 2
 mysql_duration         = 5
 mysql_allwarehouse     = false
 mysql_timeprofile      = false
 mysql_async_scale      = false
 mysql_async_client     = 10
 mysql_async_verbose    = false
 mysql_async_delay      = 1000
 mysql_connect_pool     = false
}

hammerdb>buildschema
Error: Cannot build schema with Virtual Users active, destroy Virtual Users first

hammerdb>vudestroy
vudestroy success

hammerdb>buildschema
Script cleared
Building 500 Warehouses(s) with 1 Virtual User
Ready to create a 500 Warehouse MySQL TPROC-C schema
in host 10.224.204.74:3306 under user HAMMERDB in database TPCC with storage engine INNODB?
Enter yes or no: replied yes
Vuser 1 created - WAIT IDLE
Vuser 1:RUNNING
Vuser 1:CREATING TPCC SCHEMA
Vuser 1:Ssl_cipher
Vuser 1:CHECKING IF DATABASE tpcc EXISTS
Vuser 1:Empty database tpcc exists
Vuser 1:Using existing empty Database tpcc for Schema build
Vuser 1:CREATING TPCC TABLES
Error in Virtual User 1: expected version number but got "8.4.6-commercial"
Vuser 1:FINISHED FAILED
ALL VIRTUAL USERS COMPLETE
Schema Build jobid=6A2A655F695203E293038303

Im getting this error, how do I bypass it?

**Comment by sm-shaw** [comment]
Yes the comparison uses semantic versioning https://semver.org/ so  "8.4.6-commercial" is not valid under this and errors with expected version number but got "8.4.6-commercial". The commit above relaxes this check by only checking what is a valid version number and ignoring the suffix.  This will be included in v6.0.

**Comment by shatshen** [comment]
For now do you have a temporary solution or script to fix this?

**Comment by sm-shaw** [comment]
After the schema build do something like this to redefine the table. But from v6.0 it won't complain about the non-compliant name.
```
RENAME TABLE `history` TO `history_old`;

CREATE TABLE `history` (
  `h_c_id` INT NULL,
  `h_c_d_id` INT NULL,
  `h_c_w_id` INT NULL,
  `h_d_id` INT NULL,
  `h_w_id` INT NULL,
  `h_date` DATETIME NULL,
  `h_amount` DECIMAL(6, 2) NULL,
  `h_data` VARCHAR(24) BINARY NULL,
  `id` INT NOT NULL AUTO_INCREMENT INVISIBLE,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

INSERT INTO `history` (
  `h_c_id`,
  `h_c_d_id`,
  `h_c_w_id`,
  `h_d_id`,
  `h_w_id`,
  `h_date`,
  `h_amount`,
  `h_data`
)
SELECT
  `h_c_id`,
  `h_c_d_id`,
  `h_c_w_id`,
  `h_d_id`,
  `h_w_id`,
  `h_date`,
  `h_amount`,
  `h_data`
FROM `history_old`;
```

**Comment by shatshen** [comment]
It seems I'm unable to build the schema at all because this server, I'm doing the HammerDB workload testing on, already has the InnoDB Cluster being active. The error as shown below seems to be pointing towards the configuration, **enforce-gtid-consistency=ON** is the one blocking HammerDB from building the schema:
Vuser 17:Stock done
Vuser 17:Loading District
Vuser 17:District done
Vuser 17:Loading Stock Wid=500
Vuser 17:Loading Stock - 20000
Vuser 17:Loading Stock - 40000
Vuser 17:Loading Stock - 60000
Vuser 17:Loading Stock - 80000
Vuser 17:Loading Stock - 100000
Vuser 17:Stock done
Vuser 17:Loading District
Vuser 17:District done
Vuser 17:Loading Customer for DID=1 WID=466
Error in Virtual User 17: mysql::exec/db server: The table does not comply with the requirements by an external plugin.
Vuser 17:FINISHED FAILED

Are there any other alternatives to fix this issue?

**Comment by sm-shaw** [comment]
Yes 3 options:
1. If confident enough modify the source code and build from source. 
2. If using the GUI - start a build, stop it, destroy virtual users, delete the schema at a mysql prompt. Modify the history table as above in the script editor. Create virtual users and run. It will run a modified build. 
3. As (2) but in the CLI use savescript to save the build script, modify it in an editor and use customscript  to load it, create VU and run.

**Comment by sm-shaw** [comment]
BTW - for step 1 if you can build from source you can also build the current master branch that includes the update.

**Pull request merged**
